import Vue from 'vue'
import { Button, Row, Col, Container, Header, Aside, Menu, MenuItem, MenuItemGroup, Submenu, Main, Carousel, CarouselItem, Input, Tag, Form, FormItem, Card, Tabs, TabPane, Table, TableColumn, Select, Option, Upload, Avatar, Checkbox, DatePicker, Tooltip, Message, Notification, Pagination, Alert, Loading, Drawer, Dialog, Tree, Autocomplete } from 'element-ui'

Vue.use(Button)
Vue.use(Row)
Vue.use(Col)
Vue.use(Container)
Vue.use(Header)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Submenu)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(Input)
Vue.use(Tag)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Card)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Select)
Vue.use(Option)
Vue.use(Upload)
Vue.use(Avatar)
Vue.use(Checkbox)
Vue.use(DatePicker)
Vue.use(Tooltip)
Vue.use(Pagination)
Vue.use(Alert)
Vue.use(Loading)
Vue.use(Drawer)
Vue.use(Dialog)
Vue.use(Tree)
Vue.use(Autocomplete)
Vue.prototype.$message = Message
Vue.prototype.$notify = Notification
